from dataclasses import dataclass, field

from models.professor import Professor

@dataclass
class Course:
    
    #This will be auto-generated by the database later when we implement the database layer, 
    # but for now we can just set it manually when creating a new course.
    id: int 
    name: str
    code: str
    professor_id: int | None
    description: str
    professor_id: int | None
    enrolled_students: list = field(default_factory=list)
