from dataclasses import dataclass

@dataclass
class Professor:


    #This will be auto-generated by the database later when we implement the database layer, 
    # but for now we can just set it manually when creating a new professor.
    id: int | None
    first_name: str
    last_name: str
    department: str | None
    email: str
    