
from dataclasses import dataclass


@dataclass
class Student:

    #This will be auto-generated by the database later when we implement the database layer, 
    # but for now we can just set it manually when creating a new student.
    id: int
    first_name: str
    last_name: str
    major: str
    email: str
    year: str
